
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kkogkkog;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE